//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.12 at 01:25:01 AM AEST 
//


package sample.my.web_service_app;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the sample.my.web_service_app package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: sample.my.web_service_app
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetGcdList }
     * 
     */
    public GetGcdList createGetGcdList() {
        return new GetGcdList();
    }

    /**
     * Create an instance of {@link GetGcdSum }
     * 
     */
    public GetGcdSum createGetGcdSum() {
        return new GetGcdSum();
    }

    /**
     * Create an instance of {@link GetGcdSumResponse }
     * 
     */
    public GetGcdSumResponse createGetGcdSumResponse() {
        return new GetGcdSumResponse();
    }

    /**
     * Create an instance of {@link GetGcdListResponse }
     * 
     */
    public GetGcdListResponse createGetGcdListResponse() {
        return new GetGcdListResponse();
    }

    /**
     * Create an instance of {@link GetGcd }
     * 
     */
    public GetGcd createGetGcd() {
        return new GetGcd();
    }

    /**
     * Create an instance of {@link GetGcdResponse }
     * 
     */
    public GetGcdResponse createGetGcdResponse() {
        return new GetGcdResponse();
    }

}
