//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.12 at 01:25:01 AM AEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://my.sample/web-service-app", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package sample.my.web_service_app;
